/**
 * Mock data for portal pages during development
 * These will be replaced by real database queries once the backend is connected
 */

import type { PublicQuoteData, PublicInvoiceData } from './types';

export const MOCK_QUOTE: PublicQuoteData = {
  id: 'qt-mock-001',
  quoteNumber: 'QT-1005',
  title: 'Website Redesign & Development',
  currency: 'USD',
  status: 'sent',
  issueDate: '2026-03-15',
  expirationDate: '2026-04-15',
  isExpired: false,
  blocks: [
    {
      id: 'block-1',
      type: 'header',
      content: { text: 'Project Overview', level: 2, alignment: 'left' as const },
      createdAt: '2026-03-15T00:00:00Z',
      updatedAt: '2026-03-15T00:00:00Z',
    },
    {
      id: 'block-2',
      type: 'text',
      content: {
        html: '<p>We are excited to propose a complete website redesign for your business. This project includes modern UI/UX design, responsive development, CMS integration, and comprehensive SEO optimization to ensure your online presence drives results.</p>',
        alignment: 'left' as const,
      },
      createdAt: '2026-03-15T00:00:00Z',
      updatedAt: '2026-03-15T00:00:00Z',
    },
  ],
  lineItems: [
    {
      id: 'li-1',
      name: 'UI/UX Design',
      description: 'Complete design system, wireframes, and high-fidelity mockups for all pages',
      quantity: 1,
      rate: 3500,
      amount: 3500,
      unit: 'project',
    },
    {
      id: 'li-2',
      name: 'Frontend Development',
      description: 'Responsive Next.js implementation with animations and interactions',
      quantity: 80,
      rate: 150,
      amount: 12000,
      unit: 'hour',
    },
    {
      id: 'li-3',
      name: 'CMS Integration',
      description: 'Headless CMS setup with content models and admin dashboard',
      quantity: 1,
      rate: 2500,
      amount: 2500,
      unit: 'project',
    },
    {
      id: 'li-4',
      name: 'SEO Optimization',
      description: 'Technical SEO audit, meta tag optimization, and sitemap setup',
      quantity: 1,
      rate: 1200,
      amount: 1200,
      unit: 'project',
    },
  ],
  settings: {
    requireSignature: true,
    autoConvertToInvoice: true,
    depositRequired: true,
    depositType: 'percentage',
    depositValue: 30,
    showLineItemPrices: true,
    allowPartialAcceptance: false,
    currency: 'USD',
    taxInclusive: false,
  },
  totals: {
    subtotal: 19200,
    discountType: 'percentage',
    discountValue: 5,
    discountAmount: 960,
    taxTotal: 0,
    total: 18240,
  },
  notes: 'Timeline: Estimated 8-10 weeks from project kickoff. We will provide weekly progress updates and milestone reviews.',
  terms: 'Payment terms: 30% deposit upon acceptance, 40% at design approval, 30% upon project completion. All work is subject to our standard service agreement.',
  business: {
    name: 'Pixel Studio',
    email: 'hello@pixelstudio.design',
    phone: '(555) 234-5678',
    address: '123 Creative Blvd, Suite 400\nSan Francisco, CA 94102',
    logoUrl: null,
    website: 'https://pixelstudio.design',
  },
  client: {
    name: 'Sarah Johnson',
    email: 'sarah@acmecorp.com',
    company: 'Acme Corporation',
    address: '456 Business Ave\nNew York, NY 10001',
  },
  branding: {
    primaryColor: '#3B82F6',
    accentColor: '#8B5CF6',
    logoUrl: null,
    companyName: 'Pixel Studio',
    contactEmail: 'hello@pixelstudio.design',
    contactPhone: '(555) 234-5678',
  },
};

export const MOCK_INVOICE: PublicInvoiceData = {
  id: 'inv-mock-001',
  invoiceNumber: 'INV-2026-0045',
  title: 'Website Redesign - Phase 1 Payment',
  currency: 'USD',
  status: 'sent',
  issueDate: '2026-03-15',
  dueDate: '2026-04-14',
  isOverdue: false,
  daysOverdue: 0,
  lineItems: [
    {
      id: 'ili-1',
      name: 'UI/UX Design',
      description: 'Complete design system, wireframes, and high-fidelity mockups',
      quantity: 1,
      rate: 3500,
      amount: 3500,
      taxRate: null,
      taxAmount: 0,
      sortOrder: 0,
    },
    {
      id: 'ili-2',
      name: 'Frontend Development',
      description: 'Responsive Next.js implementation (Phase 1 - 40 hours)',
      quantity: 40,
      rate: 150,
      amount: 6000,
      taxRate: null,
      taxAmount: 0,
      sortOrder: 1,
    },
    {
      id: 'ili-3',
      name: 'Project Management',
      description: 'Planning, coordination, and weekly progress updates',
      quantity: 10,
      rate: 120,
      amount: 1200,
      taxRate: null,
      taxAmount: 0,
      sortOrder: 2,
    },
  ],
  settings: {
    currency: 'USD',
    showLineItemPrices: true,
    paymentTerms: 'net30',
    lateFeeEnabled: false,
    lateFeeType: 'percentage',
    lateFeeValue: 0,
    reminderEnabled: true,
    reminderDays: [7, 3, 1],
  },
  totals: {
    subtotal: 10700,
    discountType: null,
    discountValue: null,
    discountAmount: 0,
    taxTotal: 0,
    total: 10700,
    amountPaid: 0,
    amountDue: 10700,
  },
  notes: 'Thank you for your business! This invoice covers the first phase of the website redesign project.',
  terms: 'Payment is due within 30 days of invoice date. Late payments may be subject to a 1.5% monthly finance charge.',
  business: {
    name: 'Pixel Studio',
    email: 'hello@pixelstudio.design',
    phone: '(555) 234-5678',
    address: '123 Creative Blvd, Suite 400\nSan Francisco, CA 94102',
    logoUrl: null,
    website: 'https://pixelstudio.design',
  },
  client: {
    name: 'Sarah Johnson',
    email: 'sarah@acmecorp.com',
    company: 'Acme Corporation',
    address: '456 Business Ave\nNew York, NY 10001',
  },
  branding: {
    primaryColor: '#3B82F6',
    accentColor: '#8B5CF6',
    logoUrl: null,
    companyName: 'Pixel Studio',
    contactEmail: 'hello@pixelstudio.design',
    contactPhone: '(555) 234-5678',
  },
  payments: [],
  canPay: true,
  quoteReference: { id: 'qt-mock-001', quoteNumber: 'QT-1005' },
};

export const MOCK_INVOICE_OVERDUE: PublicInvoiceData = {
  ...MOCK_INVOICE,
  id: 'inv-mock-002',
  invoiceNumber: 'INV-2026-0032',
  title: 'Branding Package - Final Payment',
  status: 'overdue',
  issueDate: '2026-02-01',
  dueDate: '2026-03-03',
  isOverdue: true,
  daysOverdue: 15,
  lineItems: [
    {
      id: 'ili-o1',
      name: 'Brand Identity Design',
      description: 'Logo design, color palette, typography system',
      quantity: 1,
      rate: 4500,
      amount: 4500,
      taxRate: null,
      taxAmount: 0,
      sortOrder: 0,
    },
    {
      id: 'ili-o2',
      name: 'Brand Guidelines Document',
      description: '40-page comprehensive brand usage guide',
      quantity: 1,
      rate: 1500,
      amount: 1500,
      taxRate: null,
      taxAmount: 0,
      sortOrder: 1,
    },
  ],
  totals: {
    subtotal: 6000,
    discountType: null,
    discountValue: null,
    discountAmount: 0,
    taxTotal: 0,
    total: 6000,
    amountPaid: 3000,
    amountDue: 3000,
  },
  payments: [
    {
      id: 'pay-1',
      amount: 3000,
      paymentMethod: 'credit_card',
      processedAt: '2026-02-15T14:30:00Z',
      status: 'succeeded',
    },
  ],
  quoteReference: null,
};
