#!/usr/bin/env bash
# ===========================================
# Oreko — Interactive Setup Script
# ===========================================
# Generates a .env file with sensible defaults and auto-generated secrets.
#
# Usage:
#   ./scripts/setup.sh

set -euo pipefail

ENV_FILE=".env"

echo "======================================"
echo "  Oreko Setup"
echo "======================================"
echo ""

if [ -f "$ENV_FILE" ]; then
  printf "An .env file already exists. Overwrite? [y/N] "
  read -r answer
  if [[ ! "$answer" =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 0
  fi
fi

# ---- Auto-generate secrets ----
NEXTAUTH_SECRET=$(openssl rand -base64 32)
POSTGRES_PASSWORD=$(openssl rand -hex 16)

# ---- Deployment mode ----
echo "Choose deployment mode:"
echo "  1) Simple  — web + postgres only (recommended for most users)"
echo "  2) Full    — web + postgres + Traefik reverse proxy with auto-SSL"
echo ""
printf "Selection [1]: "
read -r mode
mode=${mode:-1}

if [[ "$mode" == "2" ]]; then
  COMPOSE_FILE="docker-compose.prod.yml"
  printf "Domain name (e.g. quotes.example.com): "
  read -r DOMAIN
  DOMAIN=${DOMAIN:?Domain is required for full deployment}
  printf "Email for Let's Encrypt SSL certificates: "
  read -r ACME_EMAIL
  ACME_EMAIL=${ACME_EMAIL:?Email is required for SSL}
  NEXTAUTH_URL="https://${DOMAIN}"
else
  COMPOSE_FILE="docker-compose.simple.yml"
  printf "App URL [http://localhost:3000]: "
  read -r NEXTAUTH_URL
  NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
  DOMAIN=""
  ACME_EMAIL=""
fi

# ---- Optional services ----
echo ""
echo "Optional integrations (press Enter to skip):"
echo ""

printf "Stripe secret key: "
read -r STRIPE_SECRET_KEY

printf "Stripe publishable key: "
read -r STRIPE_PUBLISHABLE_KEY

printf "Stripe webhook secret: "
read -r STRIPE_WEBHOOK_SECRET

printf "Resend API key (for emails): "
read -r RESEND_API_KEY

printf "Email from address [noreply@oreko.dev]: "
read -r EMAIL_FROM
EMAIL_FROM=${EMAIL_FROM:-noreply@oreko.dev}

# ---- Write .env ----
cat > "$ENV_FILE" <<EOF
# ===========================================
# Oreko Environment (generated by setup.sh)
# ===========================================

# Deployment
COMPOSE_FILE=${COMPOSE_FILE}

# Application
NODE_ENV=production
NEXTAUTH_URL=${NEXTAUTH_URL}
NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

# Database
POSTGRES_USER=oreko
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=oreko
DATABASE_URL=postgresql://oreko:${POSTGRES_PASSWORD}@postgres:5432/oreko?schema=public
EOF

if [[ -n "$DOMAIN" ]]; then
  cat >> "$ENV_FILE" <<EOF

# Domain & SSL
DOMAIN=${DOMAIN}
ACME_EMAIL=${ACME_EMAIL}
EOF
fi

if [[ -n "${STRIPE_SECRET_KEY:-}" ]]; then
  cat >> "$ENV_FILE" <<EOF

# Stripe
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
EOF
fi

if [[ -n "${RESEND_API_KEY:-}" ]]; then
  cat >> "$ENV_FILE" <<EOF

# Email
RESEND_API_KEY=${RESEND_API_KEY}
EMAIL_FROM="${EMAIL_FROM}"
EOF
fi

echo ""
echo "======================================"
echo "  Setup complete!"
echo "======================================"
echo ""
echo "  .env written with auto-generated secrets."
echo ""
echo "  Start Oreko:"
echo "    docker compose -f ${COMPOSE_FILE} up -d"
echo ""
if [[ "$mode" == "2" ]]; then
  echo "  Your app will be available at https://${DOMAIN}"
else
  echo "  Your app will be available at ${NEXTAUTH_URL}"
fi
echo ""
